version: "3"

services: 
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    volumes:
      - ./:/app
    ports:
      - 8080:8080
