version: "3"

services: 
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    expose:
      - '3306'
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    expose:
      - '8080'
    links:
      - db
    environment:
      - MYSQL_HOST=db
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
