FROM python:2.7-slim

RUN apt-get -y update \
&& apt-get install -y unzip wget \
&& apt-get install -y -qq --no-install-recommends python-mysqldb \
&& apt-get clean

RUN mkdir /app
WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -t lib -r ./requirements.txt

CMD yes | dev_appserver.py --host=0.0.0.0 .
