FROM python:2.7-slim

RUN apt-get -y update \
&& apt-get install -y unzip wget \
&& apt-get install -y -qq --no-install-recommends python-mysqldb \
&& apt-get clean

#Setup the python path so that it finds the MySQLdb dist package
#(not setup by default on python dockerfile for some reason)
ENV PYTHONPATH $PYTHONPATH:/usr/lib/python2.7/dist-packages

RUN wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.73.zip && mv google_appengine_1.9.73.zip /tmp/gae.zip
RUN printf "opt_in: false\ntimestamp: 0.0" > /.appcfg_nag
RUN cd /usr/local && unzip /tmp/gae.zip && rm /tmp/gae.zip
ENV PATH $PATH:/usr/local/google_appengine/

RUN mkdir /app
WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -r ./requirements.txt

CMD yes | dev_appserver.py --host=0.0.0.0 .
